
[[constraint]]
  branch = "master"
  name = "gonum.org/v1/gonum"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/logrusorgru/aurora"

[[constraint]]
  branch = "master"
  name = "github.com/sparrc/go-ping"
